config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'
  resources :jobs, only: [:show, :new, :create, :edit, :update]
  resources :companies, only: [:show, :new, :create, :edit, :update]
  resources :categories, only: [:show, :new, :create, :edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :jobs

  validates :name, presence: true
  validates :name, uniqueness: true
end

app/models/company.rb
class Company < ApplicationRecord
  has_many :jobs

  def premium?
    jobs.size >= 5
  end

end

app/models/job.rb
class Job < ApplicationRecord
  belongs_to :company
  belongs_to :category

  validates :title, presence: { message: "can't be blank"}
  validates :location, presence: { message: "can't be blank"}
  validates :description, presence: { message: "can't be blank"}
  validates :category, presence: { message: "can't be blank"}

  def expired?
     Date.today >= (created_at.to_date + 90)
  end

  def recent?
    Date.today <= (created_at.to_date + 5)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def show
    @category = Category.find(params[:id])
  end

  def new
    @category = Category.new
  end

  def create
    category_params = params.require(:category).permit(:name)
    @category = Category.new(category_params)

    if @category.save
      redirect_to category_url(@category)
    else
      flash.now[:alert]= 'Não é possível cadastrar categoria'
      render :new
    end
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    category_params = params.require(:category).permit(:name)
    category = Category.find(params[:id])

    if category.update(category_params)
      redirect_to category_url(category)
    else
      @category = Category.find(params[:id])
      flash.now[:alert] = 'Não é possível atualizar categoria'
      render :edit
    end
  end

end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  def new
    @company = Company.new
  end

  def create
    company = Company.new(params_company)
    company.save
    redirect_to company_url(company)
  end

  def show
    @company = Company.find(params[:id])
  end

  def edit
    @company = Company.find(params[:id])
  end

  def update
    company = Company.update(params_company)
    redirect_to company_url(company)
  end

  private

  def params_company
    params.require(:company).permit(:name, :location, :mail, :phone)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @jobs = Job.all
    @companies = Company.all
    @categories = Category.all
  end

end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController

  def show
      @job = Job.find(params[:id])
  end

  def new
    @job = Job.new
    @companies = Company.all
    @categories = Category.all
  end

  def create
    @job = Job.new(params_job)

    if @job.save
      redirect_to job_path(@job)
    else
      @companies = Company.all
      @categories = Category.all
      flash.now[:alert] = 'Não foi possível criar a vaga'
      render :new
    end
  end

  def edit
    @job = Job.find(params[:id])
    @companies = Company.all
    @categories = Category.all
  end

  def update
    @job = Job.find(params[:id])

    if @job.update(params_job)
      redirect_to job_path(@job)
    else
      @companies = Company.all
      @categories = Category.all
      flash.now[:alert] = 'Não foi possível atualizar a vaga'
      render :edit
    end
  end

  private

  def params_job
    params.require(:job).permit(:title, :location, :category_id, :description, :featured, :company_id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/categories/edit.html.erb
<%= form_for @category do |f_category| %>
<%= f_category.label :name, 'Nome' %>
<%= f_category.text_field :name %>
<%= f_category.submit 'Atualizar' %>

<% flash.each do |name, msg| %>
  <%= content_tag :div, msg, class: name %>
<% end %>

<% end %>

app/views/categories/new.html.erb
<%= form_for @category do |f_category| %>
  <%= f_category.label :name, 'Nome' %>
  <%= f_category.text_field :name %>
  <%= f_category.submit 'Salvar Categoria' %>

  <% flash.each do |name, msg| %>
    <%= content_tag :div, msg, class: name %>
  <% end %>

  <% @category.errors.full_messages.each do |msg| %>
      <%= msg %>
    <% end %>

<% end %>

app/views/categories/show.html.erb
<div>
  <div>
    <h1><%= @category.name %></h1>
  </div>
  <div>
    <% unless @category.jobs.empty? %>
      <%= render @category.jobs %>
      <% else %>
        Nenhuma vaga disponível
    <% end %>
  </div>
</div>
<%= link_to "Voltar", root_path%>

app/views/companies/edit.html.erb
<%= form_for @company do |f_company| %>
  <%= f_company.label :name, 'Nome' %>
  <%= f_company.text_field :name%>
  <%= f_company.label :location, 'Local' %>
  <%= f_company.text_field :location %>
  <%= f_company.label :mail, 'E-mail' %>
  <%= f_company.text_field :mail %>
  <%= f_company.label :phone, 'Telefone' %>
  <%= f_company.text_field :phone %>
  
  <%= f_company.submit 'Atualizar' %>
<% end %>

app/views/companies/new.html.erb
<%= form_for @company do |f| %>
  <%= f.label :name, 'Nome' %>
  <%= f.text_field :name %>
  <%= f.label :location, 'Local'%>
  <%= f.text_field :location%>
  <%= f.label :mail, 'Email'%>
  <%= f.text_field :mail%>
  <%= f.label :phone, 'Telefone'%>
  <%= f.text_field :phone%>

  <%= f.submit 'Criar Empresa'%>

  <%= link_to "Voltar", root_path %>


<% end %>

app/views/companies/show.html.erb
<div>
  <div>
    <h1><%= @company.name %></h1>
    <% if @company.premium? %>
      <%= image_tag "estrela.png"%>
    <% end %>
    <%= @company.location%>
    <%= @company.mail%>
    <%= @company.phone%>
  </div>
  <div>
    <%unless @company.jobs.empty?%>
      <%= render @company.jobs %>
    <% else %>
      Nenhuma vaga disponível
    <% end %>
  </div>
</div>

<%= link_to "Voltar", root_path%>
<%= link_to 'editar', edit_company_path(@company)%>

app/views/home/index.html.erb
<div id="pagina">
  <div id="header">
    <h1>Emprego Já</h1>
  </div>
  <div id="menu">
    <%= link_to "Empregos", new_job_path %>
    <%= link_to "Empresa", new_company_path%>
  </div>
  <div id="conteudo">
    <% @jobs.each do |j|%>
      <div id="first-child">
        <% if j.recent? %>
          Novidade
        <% end %>
      </div>

      <ul>
        <%unless j.expired? %>
          <h1><%=link_to j.title, job_path(j.id)%></h1>
        <% end %>
        <li><%=j.company.name%></li>
        <li><%=j.location%></li>

        <%if j.featured? %>
          <li><strong><%='Destaque'%></strong></li>
        <% end %>
      </ul>
    <% end %>
  </div>
  <div id="lateral">

    <ul><strong>Empresa</strong>
      <% @companies.each do |company|%>
        <li><%= link_to company.name, company%></li>
      <% end%>
    </ul>

    <ul><strong>Categorias</strong>
      <% @categories.each do |ct|%>
        <li><%= link_to ct.name, category_path(ct.id) %></li>
      <% end%>
    </ul>

  </div>
</div>

app/views/jobs/_form.html.erb
<%= form_for @job do |f| %>
  <%= f.label :title, 'Título' %>
  <%= f.text_field :title%>
  <%= f.label :location, 'Local' %>
  <%= f.text_field :location%>
  <%= f.label :category_id, 'Categoria' %>
  <%= f.collection_select(:category_id, @categories, :id, :name)%>
  <%= f.label :company_id, 'Empresa' %>
  <%= f.collection_select(:company_id, @companies, :id, :name) %>
  <%= f.label :description, 'Descrição' %>
  <%= f.text_field :description %>
  <%= f.label :featured, 'Destaque' %>
  <%= f.check_box :featured %>

  <%= f.submit texto %>

  <%= link_to "Voltar", root_path %>

  <% flash.each do |name, msg| -%>
      <%= content_tag :div, msg, class: name %>
    <% end %>

<% end %>

app/views/jobs/_job.html.erb
  <%= job.title %>
  <%= job.category.name%>
  <%= job.location%>

app/views/jobs/edit.html.erb
<%= render partial: 'form', locals: {texto: 'Atualizar Vagas'}%>

app/views/jobs/new.html.erb
<h1>Nova Vaga</h1>
<%= render partial: 'form', locals: {texto: 'Criar Vaga'} %>

app/views/jobs/show.html.erb
<h1><%= @job.title %></h1>
<% if @job.expired? %>
  Vaga Expirada
<% end %>
<p>Categoria: <%= @job.category.name %></p>
<p>Empresa: <%=@job.company.name%></p>
<p>Descrição: <%=@job.description%></p>
<p>Local: <%=@job.location%></p>
<p><strong>Destaque</strong><%=@job.featured?%></p>
<%=link_to 'Voltar', root_path%>
<%=link_to 'Editar', edit_job_path(@job)%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Empregosja</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

  </head>

  <body>
    <%= yield %>
  </body>
</html>